DELIMITER //
DROP PROCEDURE IF EXISTS USUARIOS_CRUD;
CREATE PROCEDURE USUARIOS_CRUD(
    IN p_Method CHAR(1),
    IN p_IDUSUARIO VARCHAR(20),
    IN p_CONTRA VARCHAR(200),
    IN p_NOMBRES VARCHAR(50),
    IN p_APELLIDOS VARCHAR(50),
    IN p_IDESTADO CHAR(3),
    IN p_FOTO VARCHAR(1000)
)
BEGIN
    IF p_Method = 'C' THEN
		IF EXISTS(SELECT * FROM usuarios WHERE IDUSUARIO = p_IDUSUARIO) THEN
			SELECT 0 AS RETORNO, 'Ya existe un usario con el mismo ID' AS MSG;
        ELSE
			INSERT INTO usuarios (IDUSUARIO, CONTRA, NOMBRES, APELLIDOS, IDESTADO, FOTO)
			VALUES (p_IDUSUARIO, p_CONTRA, p_NOMBRES, p_APELLIDOS, p_IDESTADO, p_FOTO);
			SELECT 1 AS RETORNO, 'Se registró el usuario' AS MSG;
        END IF;
    ELSEIF p_Method = 'R' THEN
        SELECT * FROM usuarios;
    ELSEIF p_Method = 'U' THEN
        UPDATE usuarios
        SET
            CONTRA = COALESCE(p_CONTRA, CONTRA),
            NOMBRES = COALESCE(p_NOMBRES, NOMBRES),
            APELLIDOS = COALESCE(p_APELLIDOS, APELLIDOS),
            IDESTADO = COALESCE(p_IDESTADO, IDESTADO),
            FOTO = COALESCE(p_FOTO, FOTO)
        WHERE IDUSUARIO = p_IDUSUARIO;
		SELECT 1 AS RETORNO, 'Se actualizó el usuario' AS MSG;
    ELSEIF p_Method = 'D' THEN
        DELETE FROM usuarios WHERE IDUSUARIO = p_IDUSUARIO;
		SELECT 1 AS RETORNO, 'Se elimino al usuario' AS MSG;
    ELSE
		SELECT 0 AS RETORNO, 'No ha proporcionado un método valido' AS MSG;
	END IF;
END //

DELIMITER ;
